[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = P4BusWSNB7StMw88N
;proxy mode should be true for Ngnix to be worked
proxy_mode = True
; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
;dbfilter = ^%h$
;dbfilter = hrms
;db_name = hrms
;dbfilter = hrmsdemo
;db_name = hrmsdemo

;db_filter = fm
;db_name = fm

;db_filter = helpdesk.cirklesapp.com
;db_name = helpdesk.cirklesapp.com

;db_filter = capital.bmainternationalgroup.com
;db_name = capital.bmainternationalgroup.com

;db_filter = demoschool.adigielite.com
;db_name = demoschool.adigielite.com

;db_filter = videostreaming2
;db_name = videostreaming2

;db_filter = smartlife.adigielite.com
;db_name = smartlife.adigielite.com

;db_filter = erp.smartlifefoundation.org
;db_name = erp.smartlifefoundation.org

;db_filter = erp.adigielite.com
;db_name = erp.adigielite.com

db_filter = erp-dev.rounakcomputers.com
db_name = erp-dev.rounakcomputers.com

;db_filter = posxhero.com
;db_name = posxhero.com

#db_filter = gfsurvey.ivclao.com
#db_name = gfsurvey.ivclao.com

;db_filter = bone_crepe
;db_name = bone_crepe

#db_filter = mysmartguardians.com
#db_name = mysmartguardians.com

;db_filter = app.elcare.org
;db_name = app.elcare.org

;dbfilter = mfdemo
;db_name = mfdemo
; debug_mode = False
; email_from = False
;limit_memory_hard = 2684354560
;limit_memory_soft = 2147483648
;limit_memory_hard = 16000000000
;limit_memory_soft = 16000000000
; limit_request = 8192
limit_time_cpu = 300
limit_time_real = 600
;limit_time_cpu = 60
; limit_time_real = 120
list_db = True
;list_db = False
; log_db = False
; log_handler = [':INFO']
;log_level = info
;log_level = debug
; logfile = None
;longpolling_port = 8072
; max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
; for enable longpolling we need to enable worker
;workers = 21 
;xmlrpc = True
;xmlrpc_interface = 
;xmlrpc_port = 8069
;xmlrpcs = True
;xmlrpcs_interface = 
;xmlrpcs_port = 8071

